services:
  auth_service:
    build:
      context: ./Auth_service
      dockerfile: Dockerfile
    container_name: auth_service
    ports:
      - "8000:8000"
    env_file:
      - ./Auth_service/.env  # 👈 указываем .env
    depends_on:
      - auth_service_db
    networks:
      - zamk_net

  auth_service_db:
    image: postgres:15
    container_name: auth_service_db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      - zamk_net

volumes:
  postgres_data:

networks:
  zamk_net:
    driver: bridge
