"""Convert uuid field to UUID type

Revision ID: ee7b92996b20
Revises: c214ab5111ba
Create Date: 2025-08-03 23:15:14.569579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee7b92996b20'
down_revision: Union[str, Sequence[str], None] = 'c214ab5111ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'uuid',
               existing_type=sa.VARCHAR(),
               type_=sa.UUID(),
               existing_nullable=False,
                    postgresql_using='uuid::uuid')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'uuid',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
